### ISSUE TITLE
Web fonts don't work on deployed server

### ISSUE THREAD

**Issue by schtepf** [fau-klue/mmda-toolkit#17]
- `fonts.css` should be in `css/` subfolder rather than main folder, shouldn't it?
- `font.css` specifies absolute paths `/fonts/...` for Web fonts to be loaded; these should instead be relative paths to the local `fonts/` subdirectory in MMDA distribution
- otherwise it doesn't work in the deployed server at https://corpora.linguistik.uni-erlangen.de/mmda/

**Comment by flomei** [comment]
That was a blunder on my end.
The original error, which I overlooked, was that `fonts.css` was imported from `index.html` using a relative path, even though it was imported from the [public folder](https://cli.vuejs.org/guide/html-and-static-assets.html#the-public-folder) which requires extra consideration: i.e. prefixing it with the `<%= BASE_URL %>` template variable.
