### ISSUE TITLE
allow reloading pages

### ISSUE THREAD

**Issue by ausgerechnet** [fau-klue/mmda-toolkit#2]
current behaviour:
- reloading the current page yields 404
- similarly, browser buttons (go back one page) yield 404

**Comment by ausgerechnet** [comment]
- unfortunately, the fix did not work in our production environment
- even on the vignette (https://corpora.linguistik.uni-erlangen.de/mmda/about), reloading the page still throws a 404
- I also just realised that icons are generally missing when I'm using brave (Chromium), see my comment here: https://github.com/fau-klue/mmda-toolkit/pull/12#pullrequestreview-1264086570_

> using the development server, icons of the nav-bar (e.g. dashboard, subject, etc.) sometimes vanish when reloading the page; however, reloading once more usually solves the issue

**Comment by flomei** [comment]
I think I overlooked the fact that on production every path is prefixed with `/mmda`. This breaks the font paths and probably the rewrite rule.
I'll create a new PR which takes this into consideration.

**Comment by ausgerechnet** [comment]
configuring apache correctly did the trick. thanks!
