### ISSUE TITLE
use CLR by default in tables and semantic map

### ISSUE THREAD

**Issue by ausgerechnet** [fau-klue/mmda-toolkit#3]
current behaviour:
- when loading a new keyword / collocate table or displaying a semantic map for the first time, MI is used as association measure

desired behaviour:
- use conservative log ratio (CLR) by default

**Comment by flomei** [comment]
I created a PR under the assumption that CLR will *always* be the default whenever one navigates to a semantic map.
Is this correct or should the app remember explicit selections for each individual analysis' semantic map?

Example:
1. I create a new keyword analysis, let's call it "demo-analysis".
2. I navigate to the semantic map of "demo-analysis"
3. CLR is selected by default.
4. I change the association measure value to "MI"
5. I navigate elsewhere
6. I re-visit the semantic map of "demo-analysis"
Should the value of the association measure now be "CLR" or "MI"?

**Comment by ausgerechnet** [comment]
- ideally, the app would remember the analyst's choice for each analysis (so the answer is: "MI").
- for *new* analyses, it should be set to CLR by default.
- if this is more work than a line of code or two, setting it CLR whenever one re-visits a map will be fine ;-)
